document.writeln("   <div class=\'header-wrap\'>");
document.writeln("        <div class=\'navwrap\'>");
document.writeln("            <div id=\'nav\'>");
document.writeln("                <div class=\'navbar clearfix\'>");
document.writeln("");
document.writeln("                    <a class=\'current\' href=\'#\'>首页</a>");
document.writeln("");
document.writeln("                    <a href=\'\'><img src=\'https://img14.360buyimg.com/cms/jfs/t3364/146/1272597937/2383/5ba383e3/582146c9N2e0448cd.png\' alt=\'\'></a>");
document.writeln("");
document.writeln("");
document.writeln("                    <a href=\'\'><img src=\'https://img10.360buyimg.com/cms/jfs/t1/37576/38/1667/630/5cb5b896Ead813186/0139f7bb0353e65d.png\' alt=\'\'></a>");
document.writeln("");
document.writeln("                    <a href=\'\'><img src=\'https://img11.360buyimg.com/cms/jfs/t22252/145/1897902322/1983/8a36d7b3/5b3b1063Nceb1f0ed.png\' alt=\'\'></a>");
document.writeln("");
document.writeln("");
document.writeln("                    <a href=\'\'><img src=\'https://img11.360buyimg.com/cms/jfs/t1/37520/4/1916/2097/5cb6925dEfb281e1b/f4c99b945bc5e3d3.png\' alt=\'\'></a>");
document.writeln("");
document.writeln("                </div>");
document.writeln("                <div class=\'pros subpage\'>");
document.writeln("                    <h2>全部商品分类</h2>");
document.writeln("                    <ul class=\'prosul clearfix nav-show\' id=\'proinfo\'>");
document.writeln("                        <li class=\'food\' id=\'gg\'>");
document.writeln("");
document.writeln("                            <a class=\'ti\' href=\'#\'>奶粉辅食</a>");
document.writeln("                            <a class=\'hot\' href=\'#\'>辅食</a>");
document.writeln("");
document.writeln("                            <a href=\'#\'>辅食</a>");
document.writeln("                            <div class=\'prosmore hide\'>");
document.writeln("                                <div class=\'hh\'>");
document.writeln("                                    <dl class=\'slBlock\'>");
document.writeln("                                        <dt class=\'liTitle\'>");
document.writeln("								  <a href=\'\'>");
document.writeln("");
document.writeln("								  婴儿奶粉</a>");
document.writeln("								</dt>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>1段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>2段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>3段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>4段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'/\'>孕妈奶粉</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>有机奶粉</a></dd>");
document.writeln("                                        <dd class=\'liItem lastItem\'><a href=\'\'>特殊配方</a></dd>");
document.writeln("");
document.writeln("                                    </dl>");
document.writeln("");
document.writeln("                                    <dl class=\'slBlock\'>");
document.writeln("                                        <dt class=\'liTitle\'>");
document.writeln("									  <a href=\'\'> 婴儿奶粉</a>");
document.writeln("									</dt>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>1段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>2段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>3段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>4段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'/\'>孕妈奶粉</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>有机奶粉</a></dd>");
document.writeln("                                        <dd class=\'liItem lastItem\'><a href=\'\'>特殊配方</a></dd>");
document.writeln("");
document.writeln("                                    </dl>");
document.writeln("                                    <dl class=\'slBlock\'>");
document.writeln("                                        <dt class=\'liTitle\'>");
document.writeln("										  <a href=\'\'>");
document.writeln("		");
document.writeln("										  婴儿奶粉</a>");
document.writeln("										</dt>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>1段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>2段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>3段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>4段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'/\'>孕妈奶粉</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>有机奶粉</a></dd>");
document.writeln("                                        <dd class=\'liItem lastItem\'><a href=\'\'>特殊配方</a></dd>");
document.writeln("");
document.writeln("                                    </dl>");
document.writeln("                                    <dl class=\'slBlock\'>");
document.writeln("                                        <dt class=\'liTitle\'>");
document.writeln("									  <a href=\'\'>");
document.writeln("	");
document.writeln("									  婴儿奶粉</a>");
document.writeln("									</dt>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>1段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>2段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>3段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>4段</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'/\'>孕妈奶粉</a></dd>");
document.writeln("                                        <dd class=\'liItem \'><a href=\'\'>有机奶粉</a></dd>");
document.writeln("                                        <dd class=\'liItem lastItem\'><a href=\'\'>特殊配方</a></dd>");
document.writeln("");
document.writeln("                                    </dl>");
document.writeln("                                </div>");
document.writeln("                                <div class=\'sub-right\'>");
document.writeln("                                    <ul class=\'sub-brands clearfix\'>");
document.writeln("                                        <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                            <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                        </li>");
document.writeln("                                        <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                            <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                        </li>");
document.writeln("");
document.writeln("                                        <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                            <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                        </li>");
document.writeln("");
document.writeln("                                        <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                            <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                        </li>");
document.writeln("                                        <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                            <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                            <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                            </li>");
document.writeln("                                    </ul>");

document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'food\' id=\'gg\'>");
document.writeln("");
document.writeln("                                <a class=\'ti\' href=\'#\'>尿裤用品</a>");
document.writeln("                                <a class=\'hot\' href=\'#\'>尿裤</a>");
document.writeln("                                <a href=\'#\'>用品</a>");
document.writeln("                                <div class=\'prosmore hide\'>");
document.writeln("                                    <div class=\'hh\'>");
document.writeln("                                        <dl class=\'slBlock\'>");
document.writeln("                                            <dt class=\'liTitle\'>");
document.writeln("										  <a href=\'\'>");
document.writeln("		");
document.writeln("										 尿裤用品</a>");
document.writeln("										</dt>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>1段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>2段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>3段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>4段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'/\'>孕妈奶粉</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>有机奶粉</a></dd>");
document.writeln("                                            <dd class=\'liItem lastItem\'><a href=\'\'>特殊配方</a></dd>");
document.writeln("");
document.writeln("                                        </dl>");
document.writeln("");
document.writeln("                                        <dl class=\'slBlock\'>");
document.writeln("                                            <dt class=\'liTitle\'>");
document.writeln("											  <a href=\'\'> 婴儿奶粉</a>");
document.writeln("											</dt>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>1段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>2段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>3段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>4段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'/\'>孕妈奶粉</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>有机奶粉</a></dd>");
document.writeln("                                            <dd class=\'liItem lastItem\'><a href=\'\'>特殊配方</a></dd>");
document.writeln("");
document.writeln("                                        </dl>");
document.writeln("                                        <dl class=\'slBlock\'>");
document.writeln("                                            <dt class=\'liTitle\'>");
document.writeln("												  <a href=\'\'>");
document.writeln("				");
document.writeln("												  婴儿奶粉</a>");
document.writeln("												</dt>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>1段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>2段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>3段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>4段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'/\'>孕妈奶粉</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>有机奶粉</a></dd>");
document.writeln("                                            <dd class=\'liItem lastItem\'><a href=\'\'>特殊配方</a></dd>");
document.writeln("");
document.writeln("                                        </dl>");
document.writeln("                                        <dl class=\'slBlock\'>");
document.writeln("                                            <dt class=\'liTitle\'>");
document.writeln("											  <a href=\'\'>");
document.writeln("			");
document.writeln("											  婴儿奶粉</a>");
document.writeln("											</dt>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>1段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>2段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>3段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>4段</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'/\'>孕妈奶粉</a></dd>");
document.writeln("                                            <dd class=\'liItem \'><a href=\'\'>有机奶粉</a></dd>");
document.writeln("                                            <dd class=\'liItem lastItem\'><a href=\'\'>特殊配方</a></dd>");
document.writeln("");
document.writeln("                                        </dl>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\'sub-right\'>");
document.writeln("                                        <ul class=\'sub-brands clearfix\'>");
document.writeln("                                            <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                            </li>");
document.writeln("                                            <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                            </li>");
document.writeln("                                            <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                                <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                    <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                                </li>");
document.writeln("");
document.writeln("                                                <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                    <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                                </li>");
document.writeln("");
document.writeln("                                                <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                    <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                                </li>");
document.writeln("                                        </ul>");

document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("");
document.writeln("                                </li>");
document.writeln("                                <li class=\'food\' id=\'gg\'>");
document.writeln("");
document.writeln("                                    <a class=\'ti\' href=\'#\'>旅游</a>");
document.writeln("                                    <a class=\'hot\' href=\'#\'>酒店</a>");
document.writeln("                                    <a href=\'#\'>旅游</a>");
document.writeln("                                    <div class=\'prosmore hide\'>");
document.writeln("                                        <div class=\'hh\'>");
document.writeln("                                            <dl class=\'slBlock\'>");
document.writeln("                                                <dt class=\'liTitle\'>");
document.writeln("											  <a href=\'\'>");
document.writeln("			");
document.writeln("											  婴儿奶粉</a>");
document.writeln("											</dt>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>1段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>2段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>3段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>4段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'/\'>孕妈奶粉</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>有机奶粉</a></dd>");
document.writeln("                                                <dd class=\'liItem lastItem\'><a href=\'\'>特殊配方</a></dd>");
document.writeln("");
document.writeln("                                            </dl>");
document.writeln("");
document.writeln("                                            <dl class=\'slBlock\'>");
document.writeln("                                                <dt class=\'liTitle\'>");
document.writeln("												  <a href=\'\'> 婴儿奶粉</a>");
document.writeln("												</dt>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>1段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>2段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>3段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>4段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'/\'>孕妈奶粉</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>有机奶粉</a></dd>");
document.writeln("                                                <dd class=\'liItem lastItem\'><a href=\'\'>特殊配方</a></dd>");
document.writeln("");
document.writeln("                                            </dl>");
document.writeln("                                            <dl class=\'slBlock\'>");
document.writeln("                                                <dt class=\'liTitle\'>");
document.writeln("													  <a href=\'\'>");
document.writeln("					");
document.writeln("													  婴儿奶粉</a>");
document.writeln("													</dt>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>1段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>2段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>3段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>4段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'/\'>孕妈奶粉</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>有机奶粉</a></dd>");
document.writeln("                                                <dd class=\'liItem lastItem\'><a href=\'\'>特殊配方</a></dd>");
document.writeln("");
document.writeln("                                            </dl>");
document.writeln("                                            <dl class=\'slBlock\'>");
document.writeln("                                                <dt class=\'liTitle\'>");
document.writeln("												  <a href=\'\'>");
document.writeln("				");
document.writeln("												  婴儿奶粉</a>");
document.writeln("												</dt>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>1段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>2段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>3段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>4段</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'/\'>孕妈奶粉</a></dd>");
document.writeln("                                                <dd class=\'liItem \'><a href=\'\'>有机奶粉</a></dd>");
document.writeln("                                                <dd class=\'liItem lastItem\'><a href=\'\'>特殊配方</a></dd>");
document.writeln("");
document.writeln("                                            </dl>");
document.writeln("                                        </div>");
document.writeln("                                        <div class=\'sub-right\'>");
document.writeln("                                            <ul class=\'sub-brands clearfix\'>");
document.writeln("                                                <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                    <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                                </li>");
document.writeln("                                                <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                    <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                                </li>");
document.writeln("");
document.writeln("                                                <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                    <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                                </li>");
document.writeln("");
document.writeln("                                                <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                    <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                                </li>");
document.writeln("                                                <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                    <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                                    <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                        <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                                    </li>");
document.writeln("");
document.writeln("                                                    <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                        <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                                    </li>");
document.writeln("");
document.writeln("                                                    <li class=\'ff\' style=\'float: left;margin: 10px 20px 20px 10px;\'>");
document.writeln("");
document.writeln("                                                        <img src=\'https://img13.360buyimg.com/cms/jfs/t5533/129/344931885/7279/c5d0bdb/58fd9cf8Ncb8bd9b5.jpg!q90\' style=\'opacity: 1;\'>");
document.writeln("");
document.writeln("                                                    </li>");
document.writeln("                                            </ul>");

document.writeln("                                        </div>");
document.writeln("                                    </div>");
document.writeln("");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\'food\' id=\'gg\'>");
document.writeln("");
document.writeln("                                        <a class=\'ti\' href=\'#\'>生活</a>");
document.writeln("                                        <a href=\'#\'>婚纱摄影</a>");
document.writeln("                                        <a href=\'#\'>写真</a>");
document.writeln("");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\'food\' id=\'gg\'>");
document.writeln("");
document.writeln("                                        <a class=\'ti\' href=\'#\'>丽人</a>");
document.writeln("                                        <a href=\'#\'>美发</a>");
document.writeln("                                        <a href=\'#\'>美容美体</a>");
document.writeln("");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\'food\' id=\'gg\'>");
document.writeln("");
document.writeln("                                        <a class=\'ti\' href=\'#\'>商品</a>");
document.writeln("                                        <a href=\'#\'>服装</a>");
document.writeln("                                        <a href=\'#\'>鞋靴</a>");
document.writeln("");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\'food\' id=\'gg\'>");
document.writeln("");
document.writeln("                                        <a class=\'ti\' href=\'#\'>商品</a>");
document.writeln("                                        <a href=\'#\'>服装</a>");
document.writeln("                                        <a href=\'#\'>鞋靴</a>");
document.writeln("");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\'food\' id=\'gg\'>");
document.writeln("");
document.writeln("                                        <a class=\'ti\' href=\'#\'>商品</a>");
document.writeln("                                        <a href=\'#\'>服装</a>");
document.writeln("                                        <a href=\'#\'>鞋靴</a>");
document.writeln("");
document.writeln("                                    </li>");

document.writeln("");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    </div>");
(function() {

    var $subblock = $(".subpage"),
        $head = $subblock.find('h2'),
        $ul = $("#proinfo"),
        $lis = $ul.find("li"),
        inter = false;

    $head.click(function(e) {
        e.stopPropagation();
        if (!inter) {
            $ul.show();
        } else {
            $ul.hide();
        }
        inter = !inter;
    });

    $ul.click(function(event) {
        event.stopPropagation();
    });

    $(document).click(function() {
        $ul.hide();
        inter = !inter;
    });

    $lis.hover(function() {
        if (!$(this).hasClass('nochild')) {
            $(this).addClass("prosahover");
            $(this).find(".prosmore").removeClass('hide');
        }
    }, function() {
        if (!$(this).hasClass('nochild')) {
            if ($(this).hasClass("prosahover")) {
                $(this).removeClass("prosahover");
            }
            $(this).find(".prosmore").addClass('hide');
        }
    });

})();