document.writeln("<div class=\'foot-box\'>");
document.writeln("	<div class=\'foot\'>");
document.writeln("	<div class=\'foot-log\'> <i><img src=\'https://misc.360buyimg.com/mtd/pc/index_2019/1.0.0/assets/img/2ff7a1a01305c5081d75f15fa6f9b223.gif\' alt=\'\'></i> </div>");
document.writeln("	<div class=\'foot-list\'>");
document.writeln("		");
document.writeln("			<ul>");
document.writeln("                        <li class=\'fore1\'>");
document.writeln("                            <span class=\'title\'>海外保证</span>");
document.writeln("                            <a rel=\'nofollow\' href=\'\' title=\'正品保障\'>正品保障</a>");
document.writeln("                            ");
document.writeln("                        </li>");
document.writeln("                        <li class=\'fore2\'>");
document.writeln("                            <span class=\'title\'>购物指南</span>");
document.writeln("                           ");
document.writeln("                            <a rel=\'nofollow\' href=\'\' title=\'购物须知\'>购物须知</a>");
document.writeln("                            ");
document.writeln("                            <a rel=\'nofollow\' href=\'\'  title=\'帮助中心\'>帮助中心</a>");
document.writeln("                        </li>");
document.writeln("						");
document.writeln("                        <li class=\'fore3\'>");
document.writeln("                            <span class=\'title\'>售后服务</span>");
document.writeln("                            <a rel=\'nofollow\' href=\'\' title=\'价格保护\'>价格保护</a>");
document.writeln("							<a rel=\'nofollow\' href=\'\' title=\'破损包赔\'>破损包赔</a>");
document.writeln("							<a rel=\'nofollow\' href=\'\' title=\'晚到必赔\'>晚到必赔</a>");
document.writeln("							<a rel=\'nofollow\' href=\'\' title=\'闪电退款\'>闪电退款</a>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'fore4\'>");
document.writeln("                            <span class=\'title\'>商家服务</span>");
document.writeln("                            <a rel=\'nofollow\' href=\'\' title=\'平台规则\'>平台规则</a>");
document.writeln("                            <a rel=\'nofollow\' href=\'\' title=\'商家入驻\'>商家入驻</a>");
document.writeln("                            <a rel=\'nofollow\' href=\'\' title=\'服务商入驻\'>服务商入驻</a>");
document.writeln("                           ");
document.writeln("                        </li>");
document.writeln("                        <li class=\'fore5\'>");
document.writeln("                            <span class=\'title\'>专属客服</span>");
document.writeln("                            <a class=\'cs-online\' rel=\'nofollow\' href=\'\' title=\'在线客服\'>");
document.writeln("                                <i></i>在线客服");
document.writeln("                            </a>");
document.writeln("                            <a class=\'cs-tel\' rel=\'nofollow\'>客服电话<em><span>400</span>-606-9933</em></a>");
document.writeln("                            <a class=\'cs-time\' rel=\'nofollow\'>客服时间<em>9:00-24:00</em></a>");
document.writeln("                            <a class=\'cs-jimi\' rel=\'nofollow\' href=\'\' title=\'JIMI智能机器人\'>");
document.writeln("                                <i></i>JIMI智能机器人");
document.writeln("                            </a>");
document.writeln("                        </li>");
document.writeln("                    ");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("	<div class=\'foot-botm\'>Copyright © 2014-2019  JD.hk版权所有 自营经营者信息</div>");
document.writeln("		");
document.writeln("	</div>");
document.writeln("");
document.writeln("</div>");