document.writeln("<div class=\'head-box\'>");
document.writeln("        <div class=\'head\'>");
document.writeln("            <p class=\'text\'>京东首页</p>");
document.writeln("            <ul class=\'head-list\'>");
document.writeln("");
document.writeln("                <li><a href=\'http://127.0.0.1/haitunquanqiu/clie/html/login/denglu.html\'>你好，请登录 <span>|</span> </a></li>");
document.writeln("                <li>我的订单 <span>|</span></li>");
document.writeln("                <li>我的海囤全球<span>|</span></li>");
document.writeln("                <li> 关注海囤全球");
document.writeln("                    <span>|</span>");
document.writeln("                </li>");
document.writeln("                <li> 帮助中心</li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("    <div class=\'w-box\'>");
document.writeln("        <h1><img src=\'https://misc.360buyimg.com/mtd/pc/index_2019/1.0.0/assets/img/2ff7a1a01305c5081d75f15fa6f9b223.gif\' alt=\'\'></h1>");
document.writeln("        <div id=\'search-2014\'>");
document.writeln("            <div class=\'form\'>");
document.writeln("                <input type=\'text\' id=\'key\' class=\'text\' placeholder=\'膳魔师\' value=\'\'>");
document.writeln("                <button class=\'button action-search-worldwide cw-icon\'>搜索</button>");
document.writeln("            </div>");
document.writeln("            <div id=\'form-nav\'>");
document.writeln("                <a href=\'#\' target=\'_blank\' class=\'style-red\'>浪琴</a>");
document.writeln("                <a href=\'\' target=\'_blank\' class=\'style-red\'>运动</a>");
document.writeln("                <a href=\'\' target=\'_blank\' class=\'style-red\'>JM面膜</a>");
document.writeln("                <a href=\'\' target=\'_blank\' class=\'style-red\'>未来驱蚊</a>");
document.writeln("                <a href=\'\' target=\'_blank\' class=\'style-red\'>施华洛世奇天鹅系列</a>");
document.writeln("                <a href=\'\' target=\'_blank\' class=\'style-red\'>爱车呵护</a>");
document.writeln("                <a href=\'\' target=\'_blank\' class=\'style-red\'>施华洛世奇</a>");
document.writeln("                <a href=\'\' target=\'_blank\' class=\'style-red\'>AJOY SAHU</a>");
document.writeln("                <a href=\'\' target=\'_blank\' class=\'style-red\'>RT美妆蛋</a>");
document.writeln("                <a href=\'\' target=\'_blank\' class=\'style-red\'>潮电好货</a>");
document.writeln("                <a href=\'\' target=\'_blank\' class=\'style-red\'>杀菌除螨</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'w-car\'>");
document.writeln("");
document.writeln("            <i class=\'ci-left\'><img src=\'\' alt=\'\'></i>");
document.writeln("            <span>我的购物车</span>");
document.writeln("");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");